on:
    push:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"
    pull_request:
        branches:
            - main
            - "release/**"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7.0.0

            - name: Run Tests
              run: |
                cd src 
                npm test 
          
         
        
